name: Main PHP Unit Tests Coverage
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    if: "!contains(github.event.head_commit.message, '[ci]')"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        php: [8.2]
        laravel: [8, 9, 10]
        stability: [prefer-stable]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pcov, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: pcov
          tools: phpstan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.laravel }}-composer--${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.laravel }}-composer-

      - name: Add token
        run: |
          composer config github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer require "laravel/framework:${{ matrix.laravel }}.*" --no-interaction --no-update

      - name: Update dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer update --${{ matrix.stability }} --no-interaction

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"


      - name: Run Unit Tests L8
        if: startsWith(matrix.laravel, '8') == true
        run: php -d pcov.enabled=1 ./vendor/bin/paratest --testsuite='Standard' --coverage-clover='clover-L8.xml' --exclude-group skip8 --passthru-php="'-d pcov.enabled=1'"

      - name: Run Unit Tests L9 L10
        if: startsWith(matrix.laravel, '8') == false
        run: php -d pcov.enabled=1 ./vendor/bin/paratest --testsuite='Standard' --coverage-clover='clover-L${{ matrix.laravel }}.xml' --passthru-php="'-d pcov.enabled=1'"

      - name: Stash CoverageSVG
        run: |
          git stash

      - name: phpunit-coverage-badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          report: 'clover-L${{ matrix.laravel }}.xml'
          coverage_badge_path: 'output/phpunit-coverage-L${{ matrix.laravel }}.svg'
          push_badge: false

      - name: Add CoverageSVG
        run: |
          git stash
          git add output/phpunit-coverage-L${{ matrix.laravel }}.svg
          git rm clover*
          git rm build/*

      - name: update-coverage-badge
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          branch: image-data
          commit_options: '--no-verify --signoff'
          add_options: '--no-all --ignore-removal'
          file_pattern: '.phpunit.cache/* composer.lock'
          push_options: '--force'
          skip_dirty_check: true 
          skip_fetch: false   
          skip_checkout: false 
        run: |
          git stash
          git add output/phpunit-coverage-L${{ matrix.laravel }}.svg
          git rm clover*
          git rm build/*

