name: Develop PHP Unit Tests
on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci]')"
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]
        php: [8.1, 8.2]
        laravel: [8.*, 9.*, 10.*]
        stability: [prefer-dist]
        exclude:
          - laravel: 10.*
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pcov, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: pcov
          tools: phpstan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.laravel }}-composer--${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.laravel }}-composer-

      - name: Add token
        run: |
          composer config github-oauth.github.com ${{ secrets.LRL_GH_SECRET }}

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update

      - name: Update dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer update --${{ matrix.stability }} --no-interaction

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Run Unit Tests L8
        if: ${{ matrix.laravel }} == '8.*'
        run: php -d pcov.enabled=1 ./vendor/bin/paratest --testsuite='Standard' --exclude skip8 --passthru-php="'-d pcov.enabled=1'"

      - name: Run Unit Tests L9 L10
        if: ${{ matrix.laravel }} != '8.*'
        run: php -d pcov.enabled=1 ./vendor/bin/paratest --testsuite='Standard' --passthru-php="'-d pcov.enabled=1'"

      - name: Run PHPStan
        if: ${{ matrix.laravel }} != '8.*'
        run: phpstan analyse src

      - name: phpunit-coverage-badge-l9
        if: ${{ matrix.laravel }} == '9.*'
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          coverage_badge_path: 'docs/images/badges/phpunit-coverage-L9-${{ matrix.php }}-develop.svg'
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: phpunit-coverage-badge-l10
        if: ${{ matrix.laravel }} == '10.*'
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          coverage_badge_path: 'docs/images/badges/phpunit-coverage-L10-${{ matrix.php }}-develop.svg'
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
