name: PHPUnit Coverage Tests
on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ${{ matrix.os }}
    max-parallel: 1
    permissions:
      contents: write
    if: "!contains(github.event.head_commit.message, '[ci]')"
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]
        php: [8.2]
        laravel: [8.*, 9.*, 10.*]
        stability: [prefer-stable]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pcov, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: pcov
          tools: phpstan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.laravel }}-composer--${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.laravel }}-composer-

      - name: Add token
        run: |
          composer config github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update

      - name: Update dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer update --${{ matrix.stability }} --no-interaction

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Run Unit Tests L8
        if: startsWith(matrix.laravel, '8') == true
        run: php -d pcov.enabled=1 ./vendor/bin/paratest --testsuite='Standard' --exclude-group skip8 --passthru-php="'-d pcov.enabled=1'"

      - name: Run Unit Tests L9 L10
        if: startsWith(matrix.laravel, '8') == false
        run: php -d pcov.enabled=1 ./vendor/bin/paratest --testsuite='Standard' --passthru-php="'-d pcov.enabled=1'"

      - name: phpunit-coverage-badge-l8
        if: startsWith(matrix.laravel, '8') == true
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          report: 'build/clover.xml'
          coverage_badge_path: 'output/L8/phpunit-coverage-L8-develop.svg'
          push_badge: false

      - name: phpunit-coverage-badge-l9
        if: startsWith(matrix.laravel, '9') == true
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          report: 'build/clover.xml'
          coverage_badge_path: 'output/L9/phpunit-coverage-L9-develop.svg'
          push_badge: false

      - name: phpunit-coverage-badge-l10
        if: startsWith(matrix.laravel, '10') == true
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          report: 'build/clover.xml'
          coverage_badge_path: 'output/L10/phpunit-coverage-L10-develop.svg'
          push_badge: false

  updateCoverage:
    needs: test
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    if: "!contains(github.event.head_commit.message, '[ci]')"
    steps:
      - name: Git push to image-data branch L10
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./output  # default: public
          publish_branch: image-data2
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'